Vectores y operaciones

In [5]:
# Vectores
# Creando un vector con una lista simple de python

v1py = [1, 2, 3]
v2py = [4, 5, 6]

v1py + v2py

[1, 2, 3, 4, 5, 6]

In [6]:
7 * v1py

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [7]:
# Importar numpy que es la librería matemática que me permite utilizar los objetos de algebra
import numpy as np

In [8]:
# Crear un array de numpy 
v1np = np.array(v1py) # np.array([1,2,3])
v2np = np.array(v2py) # np.array([4,5,6])

In [9]:
# Sumando vectores
v1np + v2np

array([5, 7, 9])

In [10]:
# Restando vectores
v1np - v2np

array([-3, -3, -3])

In [11]:
# Multiplicación por escalar
7 * v1np

array([ 7, 14, 21])

In [14]:
# Funcion para crear vectores o arrays con 1's
vunos = np.ones(10)
vunos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [20]:
#Crear arreglos de numpy por rango
vrange = np.arange(1,4)
vrange

array([1, 2, 3])

In [21]:
#Producto punto en numpy
np.dot(v1np,v2np)

32

In [22]:
#Producto punto con sum (función nativa de python)
sum(v1np * v2np)

32

In [23]:
# Ejemplo de vectores ortogonales o perpendiculares

v1 = np.array([3,4])
v2 = np.array([4,-3])

np.dot(v1,v2)

0

In [24]:
# Ejemplo calculo norma del vector

v3 = [3,7,5,1]
np.linalg.norm(v3)

9.16515138991168

Matrices - suma, resta y multiplicación por escalar

In [25]:
A = np.array([[1, 3, 2],  #Para crear matrices van dentro de una lista 
              [1, 0, 0],  # y son listas separadas por comas
              [1, 2, 2]])

In [26]:
B = np.array([[1, 0, 5],
              [7, 5, 0],
              [2, 1, 1]])

In [27]:
# Suma de matrices
A + B

array([[2, 3, 7],
       [8, 5, 0],
       [3, 3, 3]])

In [28]:
# Resta de matrices
A - B

array([[ 0,  3, -3],
       [-6, -5,  0],
       [-1,  1,  1]])

In [29]:
# Multiplicacion de matriz por escalar
A * 5

array([[ 5, 15, 10],
       [ 5,  0,  0],
       [ 5, 10, 10]])

In [30]:
# Para ver la dimension (renglones x columnas) de mi matriz
A.shape

(3, 3)

In [31]:
# Para ver el número de elementos
A.size

9

Multiplicación de matrices

In [47]:
A = np.arange(1, 13).reshape(3, 4) #Aqui le digo que cree una matriz en el rango del 1 hasta < 13
A                                  # Y con reshape le digo que me la acomode como matriz de 3*4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [41]:
B = np.arange(8).reshape(4,2) 
B

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [42]:
A @ B #El arroba es el simbolo en python numpy para realizar la multiplicación de matrices

array([[ 40,  50],
       [ 88, 114],
       [136, 178]])

In [43]:
#Matriz identidad
I = np.eye(2) #Funcion que me permite crear matrices identidad 
I             # El parametro que recibe es el numero de r y c

array([[1., 0.],
       [0., 1.]])

In [44]:
C = np.array([[4,7],
              [2,6]])
C

array([[4, 7],
       [2, 6]])

In [45]:
I @ C

array([[4., 7.],
       [2., 6.]])

In [48]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [49]:
# Calculo del determinante de una matriz (solo funciona en matrices cuadradas)
np.linalg.det(A)

0.0

In [50]:
# Matriz transpuesta
A = np.arange(6).reshape(3, 2)
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [51]:
np.transpose(A)

array([[0, 2, 4],
       [1, 3, 5]])

In [52]:
# Matriz inversa
A = np.array([[4, 7],
              [2, 6]])

In [53]:
inv = np.linalg.inv(A)
inv

array([[ 0.6, -0.7],
       [-0.2,  0.4]])